version: "3.8"
services:
    app:
      image: ros2_rust:latest 
      stdin_open: true
      tty: true   
      #ports:
      #  - 5900 
      cap_add:
        - SYS_PTRACE
      volumes:
        - ./workspace:/home/user/workspace
        - ./library:/library
        - /tmp/.X11-unix:/tmp/.X11-unix
      environment:
        - DISPLAY=${DISPLAY}
        - NVIDIA_VISIBLE_DEVICES=all 
        - NVIDIA_DRIVER_CAPABILITIES=all
        - QT_X11_NO_MITSHM=1
        # library
        - ORT_STRATEGY=system
        - ORT_LIB_LOCATION=/home/user/library/onnxruntime-linux-x64-1.13.1
        - LIBRARY_PATH=/home/user/library/onnxruntime-linux-x64-1.13.1
      network_mode: host
      restart: always

