inference_node:
  ros__parameters:
    image_topic: "/tir/image"
    model_path:  "/home/user/workspace/yolo_tir_rust/src/yolo_tir/param/best_seq_learn.onnx"
    detection_topic: "/tir/detection"
    nms_threshold:    0.45 
    conf_threshold:   0.25
    conf_idx:       4
    cls_idx_offset:   5
    classes: ["person","bike","car","other vehicle"]